name: Maven Build and Docker Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:   # allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Cache Maven dependencies (optional but faster)
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4️⃣ Build with Maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      # 5️⃣ Log in to Docker registry
      # Set your secrets in: Settings → Secrets and variables → Actions
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/githubaction:latest
            ${{ secrets.DOCKER_USERNAME }}/githubaction:${{ github.run_number }}

      
# (Optional) Verify image
#       - name: Verify image
#         run: docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest